FROM archlinux

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm base-devel

RUN useradd user -s /bin/bash -m
RUN echo 'user ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers

RUN echo -e '[options]\nIgnorePkg = beep adduser' >> /etc/pacman.conf
RUN pacman -Sy

USER user

RUN set -eux; \
        mkdir /tmp/pikaur; \
        cd /tmp/pikaur; \
        curl -L 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pikaur' > PKGBUILD; \
        makepkg -s -i --noconfirm; \
        rm -fr /tmp/pikaur
RUN set -eux; \
        mkdir /tmp/beep; \
        curl -L 'https://raw.githubusercontent.com/archlinux/svntogit-packages/84e09941b61033322d5af0ee8da7fc48bf83e392/trunk/PKGBUILD' > /tmp/beep/PKGBUILD; \
        pikaur -P -i --noconfirm /tmp/beep/PKGBUILD;
RUN set -eux; \
        mkdir /tmp/adduser; \
        curl -L 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=adduser&id=d0fe7c75f2206003877ad7cfc3ecdc96ee6f45e9' > /tmp/adduser/PKGBUILD; \
        pikaur -P -i --noconfirm /tmp/adduser/PKGBUILD;
RUN sudo pacman -Rs pikaur --noconfirm
ADD --chown=user:user . /tmp/pikaur/
RUN set -eux; \
        cd /tmp/pikaur; \
		rm -fr ./.ruff_cache ; \
		tar --transform 's,^,pikaur-git/,' -cf pikaur-git.tar.gz . ; \
		sed -i 's/"$pkgname::.*"/"pikaur-git.tar.gz"/' PKGBUILD ; \
        makepkg -s -i --noconfirm;

RUN pikaur -Syu --verbose --pikaur-debug;

# vim: set ft=dockerfile :
