#!/bin/bash

# This file is licensed under GPLv3, see https://www.gnu.org/licenses/

if [[ ! "$(grep foobz1 PKGBUILD)" ]]  && [[ ! "$(grep foobz2 PKGBUILD)" ]] ; then
	for line in $(grep "^prepare.*()" PKGBUILD -o) ; do
		echo -e "$line {\n echo \"foo_$line\"\n }" >> PKGBUILD
	done
	for line in $(grep "^package.*()" PKGBUILD -o) ; do
		echo -e "$line {\n echo \"foo_$line\"\n }" >> PKGBUILD
	done
	echo '

prepare() {
	echo "======= Fake prepare() ======="
	echo "foobz2"
}

build() {
	echo "======= Fake build() ======="
	echo "foobz3"
}

check() {
	echo "======= Fake build() ======="
	echo "foobz3"
}

package() {
	echo "======= Fake package() ======="
	echo "foobz1"
}

' >> ./PKGBUILD
fi
/usr/bin/makepkg --skippgpcheck $@
