#!/bin/bash

# This file is licensed under GPLv3, see https://www.gnu.org/licenses/

if [[ ! "$(grep pikaur_fake_makepkg_package PKGBUILD)" ]]  && [[ ! "$(grep pikaur_fake_makepkg_prepare PKGBUILD)" ]] ; then
	for line in $(grep "^prepare_.\+()" PKGBUILD -o) ; do
		echo -e "$line {\n echo \"fake_$line\"\n }" >> PKGBUILD
	done
	for line in $(grep "^package_.\+()" PKGBUILD -o) ; do
		echo -e "$line {\n echo \"fake_$line\"\n }" >> PKGBUILD
	done

source ./PKGBUILD
	echo '

prepare() {
	echo "======= Fake prepare() ======="
	echo "pikaur_fake_makepkg_prepare"
}

build() {
	echo "======= Fake build() ======="
	echo "pikaur_fake_makepkg_build"
}

check() {
	echo "======= Fake check() ======="
	echo "pikaur_fake_makepkg_check"
}
' >> ./PKGBUILD

# shellcheck disable=SC2154
if [ "${#pkgname[@]}" -eq 1 ] ; then
		echo "
package() {
	echo '======= Fake package() ======='
	echo 'pikaur_fake_makepkg_package'
}
	" >> ./PKGBUILD
else
	# shellcheck disable=SC2154
	for _pkg_name in "${pkgname[@]}" ; do
		echo "
package_${_pkg_name}() {
	echo '======= Fake package() ======='
	echo 'pikaur_fake_makepkg_package'
}
	" >> ./PKGBUILD
	done
fi

fi
# shellcheck disable=SC2068
/usr/bin/makepkg --skippgpcheck $@
